# Generated by Django 2.2.12 on 2020-04-29 17:51

import auth_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20200429_2319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_app.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
